#! /usr/bin/env bash

# uses entr to watch for changes: http://entrproject.org

# re-run any individual .bats file when it changes. -p to postpone the first execution, since the commands below will run all the .bats files.
shopt -s globstar
# shellcheck disable=SC2012,SC2035
ls **/*.bats | entr -p bats /_ &

# re-run relevant tests when a source file changes.
echo deploy.sh | entr -p bats . &
# shellcheck disable=SC2012
ls lib/*.bash | entr bats lib .
